### ISSUE TITLE
Misuse of Markdown in README.md

### ISSUE THREAD

**Issue by jbrucker** [Pat-7-626/ku-polls#31]
In README.md you use Markdown tags for purposes that they are not intended for.

```markdown
##### Author: ...
```

The tags `#`, `##`, `###`, etc. are for section, subsection, subsubsection headers, not for formatting.
```markdown
***
```
To create a horizontal line please use 3 dashes `---`. `***` means "bold and italic" font.

**Comment by Pat-7-626** [comment]
Fixed
