### ISSUE TITLE
Please do not use Q&A writing style in README or in Project proposals

### ISSUE THREAD

**Issue by jbrucker** [Pat-7-626/ku-polls#32]
Please do not use Q&A style for section titles in README or in your project docs.

For example:
```markdown
# how do I install and run it?
```

should be (2 sections):
```markdown
## Installation

## Run
- or -
## How to Run
```
"How to Run" is a statement, not a question.

Similarly, please reword these (and use `##` level heading, not title `#`)
```markdown
# What does the UI look like?

# What does this application do?
```

**Comment by Pat-7-626** [comment]
Fixed
