### ISSUE TITLE
Poll choices should be added or changed using the admin interface.

### ISSUE THREAD

**Issue by gooddinosaur** [Pat-7-626/ku-polls#80]
(Feature 5 of Iteration1)
![image](https://github.com/user-attachments/assets/3f541b28-9d81-4cf0-bbc0-63e7aab81cb2)
In this page: `http://127.0.0.1:8000/admin/`
![image](https://github.com/user-attachments/assets/259b0b1a-7225-449d-b96a-fbd76504e6a5)

**Comment by Pat-7-626** [comment]
We do not need this feature anymore since the Vote class counts the votes with only authenticated users.
