### ISSUE TITLE
If a user selects a poll he already voted on, the list of choices shows which choice he/she previously selected.

### ISSUE THREAD

**Issue by gooddinosaur** [Pat-7-626/ku-polls#83]
From Iteration 3 Feature 4
![image](https://github.com/user-attachments/assets/86940a9a-6349-4ffa-b9f3-bef9885c7746)
It should check previous vote choice. Actually, it is great that you have a message for the previous vote, but the choice needs to be selected too.
It should be like this photo
![image](https://github.com/user-attachments/assets/aee147c5-6e7e-4884-bdb1-ce099bee33fb)

**Comment by Pat-7-626** [comment]
added it.
